# Generated by Django 6.0.4 on 2026-04-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salgadinho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flavor', models.CharField(max_length=20)),
                ('factory_day', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
