# Generated by Django 6.0.4 on 2026-04-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salgadinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salgadinho',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salgadinho',
            name='taste',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salgadinho',
            name='flavor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
